sudo: required

language: node_js
node_js:
  - "10"
  
services:
    - docker:

before_install:
    - docker build -t abd17/docker-react -f Dockerfile.dev .

script:
    - docker run abd17/docker-react npm run test -- --coverage